# @info
# https://github.community/t5/GitHub-Actions/Start-a-workflow-from-another-workflow/td-p/37586
name: main
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/JamesIves/github-pages-deploy-action#getting-started-airplane
      - name: checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@v1
        with:
          node-version: 15.0.1
      - name: install
        run: yarn
      - name: build
        run: npx tsc
      # - name: deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./public

      # release
      - name: setup-node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
